// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB5fPqbH2XgjSMelWgO66akgxs8z3xHBc',
    appId: '1:791070461892:web:6e264277107f8a6ce79e91',
    messagingSenderId: '791070461892',
    projectId: 'yhoc-22348',
    authDomain: 'yhoc-22348.firebaseapp.com',
    storageBucket: 'yhoc-22348.firebasestorage.app',
    measurementId: 'G-XVMYKYL393',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFh0Xr169b4c39bXAKSBYsorpt1NF7-Gk',
    appId: '1:791070461892:android:627c7cb7f1b112b3e79e91',
    messagingSenderId: '791070461892',
    projectId: 'yhoc-22348',
    storageBucket: 'yhoc-22348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg575BsSK1vvJz3qMt9op6KTpLlOo4BNk',
    appId: '1:791070461892:ios:1aa9e1e70d419101e79e91',
    messagingSenderId: '791070461892',
    projectId: 'yhoc-22348',
    storageBucket: 'yhoc-22348.firebasestorage.app',
    iosBundleId: 'com.example.yhoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg575BsSK1vvJz3qMt9op6KTpLlOo4BNk',
    appId: '1:791070461892:ios:1aa9e1e70d419101e79e91',
    messagingSenderId: '791070461892',
    projectId: 'yhoc-22348',
    storageBucket: 'yhoc-22348.firebasestorage.app',
    iosBundleId: 'com.example.yhoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB5fPqbH2XgjSMelWgO66akgxs8z3xHBc',
    appId: '1:791070461892:web:aef175b2812d9e73e79e91',
    messagingSenderId: '791070461892',
    projectId: 'yhoc-22348',
    authDomain: 'yhoc-22348.firebaseapp.com',
    storageBucket: 'yhoc-22348.firebasestorage.app',
    measurementId: 'G-FFRNT6VFVY',
  );
}
